### ISSUE TITLE
Set up proper database bootstrapping

### ISSUE THREAD

**Issue by steeling** [interuss/dss#111]
The grpc backend should not be in the business of creating tables in the DB. We should set up proper database migration management for any changes, and a proper bootstrapping script.

- [ ] Evaluate existing frameworks to handle database migrations
- [ ] Move database migrations into `*.sql` such that operating entities can use the migrations *without* being forced into the default database migration framework.

**Comment by charlie-pisuraj** [comment]
Hey @vosst 
So I've looked at several migration tools available and I believe we can go with this https://github.com/golang-migrate/migrate

We can have a job that runs on the cluster that inits the CRDB cluster that Bootstraps or migrates the db if it see any changes to the SQL files. To allow for early bail out of the grpc backend we will add a new table to store the version of each table and if hardcode the table version that is supported by that binary. Since CRDB supports live migration as well as doing it inside a transaction we can ensure that once the update is completed it will bump the version number of the table.

cc: @steeling @BenjaminPelletier

**Comment by BenjaminPelletier** [comment]
db-manager is this bootstrapping tool
