### ISSUE TITLE
New forks? Old forks?

### ISSUE THREAD

**Issue by NTierSoftware** [interuss/dss#118]
Dear InterUSS Project,
I'm interested in establishing a USS node using your project. As of last Fri. 9/27/19, I was working w/ your well documented version and getting Zookeeper, docker, python config'd/ installed per this:
"Directories of Interest:
datanode/docker: instructions to download and start your own datanode image as well as the source to create your own docker image to test
datanode/src: all of the source code for running the API and Interface layer
"

But it appears to have all changed? Am I no longer on the correct path?
The above seems to have been moved to legacy?: 
https://github.com/interuss/dss/tree/legacy/master

and now I see this:
https://github.com/interuss/dss
"Directories of Interest:
config/ has all of the configuration required to deploy a DSS instance to a kubernetes cluster. The README in that directory contains more information.
pkg/ contains all of the source code for the DSS. See the README in that directory for more information.
cmds/ contains entry points and docker files for the actual binaries (the http-gateway and grpc-backend)
Notes
Currently this branch only supports the Remote ID API's."

My questions:
1) Has my original install/config changed so radically? (ie. I see little to no mention of docker/python/zookeeper. Now I see a lot of mention of "Cockroach DB" that seemed to be missing as of last Friday).

2) How do I get back onto your correct install/config path so I may investigage properly the Inter-USS platform API?

Please excuse my ignorance, confusion, and all around "noob"-ness.
-John Donaldson
JD.John.Donaldson@gmail.com

**Comment by BenjaminPelletier** [comment]
Yes, the short answer is that the branch previously called "master" while the repository was the "InterUSS-Platform" is now "legacy/master" as the "dss".  The new branch (now "master") is a full rewrite to implement the ASTM UAS remote ID standard for production using CockroachDB instead of Zookeeper and Go instead of Python.

This project has had a few separate phases of development.  The Python codebase was developed before the concept of a DSS (Discovery and Synchronization Service) was named, and specifically, before the development of the upcoming ASTM UAS remote ID standard.  The Python codebase has served many purposes including involvement in NASA's Technical Capability Levels and the various flavors are now tracked under legacy/* branches.  The legacy/tcl4 branch is the most developed of these and was intended for (and most recently used in) TCL4.  The legacy/master branch (previously just "master") is strictly behind the tcl4 branch in terms of commits and investigation using the tcl4 branch will likely be more productive than legacy/master.

The original intention was that lessons learned from TCL4 would be merged back into master following TCL4.  But, these lessons have instead been incorporated into the DSS concept of the ASTM UAS remote ID standard and the upcoming strategic deconfliction standard, and the current "master" branch is an implementation of that DSS concept.  This means the Python codebase will likely not be updated substantially going forward in favor of the Go rewrite which incorporates the updated DSS concept (and therefore, lessons learned from experience with the Python codebase) and is more focused on production rather than demonstration.

If you previously checked out a branch with a different name, the only thing you need to do to continue working with that branch as before is to update the remote URL and rename the branch -- the commit content has not changed appreciably.  However, I would generally recommend against investigations on the legacy/master branch as legacy/tcl4 is more advanced in many ways and is the implementation most widely used among other investigators.  If you do not need strategic deconfliction, the master branch is the implementation of the most current DSS concept, but only supports remote ID.

Please pardon our dust for the next few weeks as we are currently transitioning from a Google open source project to a Linux Foundation project.

**Comment by NTierSoftware** [comment]
Quick reply. Thanks.
I believe we do need strategic deconfliction.
But I don't want to engage w/ old forks so I'll wrangle w/ the current master branch.

Perhaps some of this topic was previously covered in your Slack. I still wait to get an account.
https://groups.google.com/forum/#!topic/interuss-platform/dZf-7fZL8Ec

Thank you,
-JD
