### ISSUE TITLE
Tech Architecture Still Says Zookeeper - Why the switch to CockroachDB?

### ISSUE THREAD

**Issue by shortwavedave** [interuss/dss#129]
The Technical Architecture Doc in https://github.com/interuss/dss/tree/master/assets still says the DSS uses Zookeeper for coordination, but it looks like CockroachDB + gRPC has replaced it in the master branch. 

Just looking for some context - has CockroachDB replaced Zookeeper entirely and why?

**Comment by BenjaminPelletier** [comment]
We're still working through a transition to a new (basically from-scratch) Go implementation that will conform to the upcoming ASTM standard and the `assets` folder has not been updated on the master branch yet.  CockroachDB has replaced Zookeeper as the backing storage mechanism following a trade study among various alternatives that we hope to document when there is a chance, but the highlights versus Zookeeper are 1) Zookeeper has a ceiling of ~10GB of stored data, 2) CockroachDB simplifies DSS interactions with pessimistic transactions, and 3) a database enables a number of future features by implementing general queries rather than limiting information retrieval to a single key type (cell ID).  gRPC is just an internal mechanism for the API -- an HTTP interface is still exposed via bridge, and neither feature affects the backing storage approach.

**Comment by shortwavedave** [comment]
Thanks for the info @BenjaminPelletier
