### ISSUE TITLE
TCL4 Feature: Automatically expand min/max timestamp based on operations

### ISSUE THREAD

**Issue by hi-kevin** [interuss/dss#45]
**Is your feature request related to a problem? Please describe.**
When a USS registers a new Operation using the PUT /GridCellOperation endpoint, the timestamps in GridCellOperator are not updated. To update the timestamps, the USS has to then call PUT /GridCellOperator to update the timestamps... but it will clear the operations if they are not  specified, making the original PUT /GridCellOperation call pointless

**Describe the solution you'd like**
Automatically expand (decrease min, increase max) based on operation. Do not automatically set the min and max, as the USS may have reasons for setting this.

**Describe alternatives you've considered**
PATCH should be available, but it is not currently implemented.

**Comment by boguwei** [comment]
in a related vein of thought (I can open up a separate issue for this if this goes somewhere): should /GridCellOperator allow PUTs where the min/max operation times are completely in the past of the time the request was made? currently, we only check that min is less than max, but don't make a comparison against the request time.

**Comment by nasajoey** [comment]
This is a worm contained in a large can of fellow worms.  We need a standard or specification for time syncing in UTM as a whole.  Without that, we'll hit sync issues between systems.  For example, GUD will reject something that you thought was reasonable because your clock is 2 seconds ahead of GUD's clock.  If we start to add buffers to things, it is a slippery slope.  We need a time sync specification.  I've proposed one or two in the past, but did get much feedback... I think it was too early (pun intended).  We may be getting a good community together to bring this issue back to the table.

**Comment by hi-kevin** [comment]
I agree with Joey. The overall philosophy for the platform is to allow as much information as possible and allow the USSs to decide how the information should be used. This gives it more flexibility for different use cases as this industry gets worked out. 

i.e. Do you want to accept +/- 2 seconds from other USSs? Not for the platform to decide.

For example, we share timestamps in the NASA millisecond UTC format, but we accept them in all kinds of various ways, and do our best at parsing before throwing any exceptions.

**Comment by boguwei** [comment]
all great points. I'm not opposed to dumping this can of worms out somewhere else. I think allowing the USSs to decide how information should be used is so long as we can expect all USSs to share some level of consistency in interpreting the information in the first place - @nasajoey if you want to resurrect the time sync specification, I'd love to take a look at it (I think I'm ready for it now).
