### ISSUE TITLE
monitorlib PyJWT dependency update from 1.7.1 -> 2.1.0

### ISSUE THREAD

**Issue by hrishiballal** [interuss/dss#523]
**Describe the bug**
At the moment monitorlib tools require pyjwt 1.7.1, the tooling specifically infrastructure.py produces errors if a newer version of pyJWT is installed in the environment. This is not a bug per say but a question about the strategy to upgrade older libraries, is upgrading PyJWT dependency considered a priority? 

**To Reproduce**
1. Install the latest pyJWT e.g. pip install pyjwt==2.1.0
2. Run the RID Qualifier tooling e.g. `python monitoring/rid_qualifier/rid_qualifier_entry.py --auth='DummyOAuth(http://localhost:8085/token, sub=local.test)' --config=monitoring/rid_qualifier/config.json` 

**Expected behavior**
JWT tokens generated should be decoded. 

**Screenshots**
![image](https://user-images.githubusercontent.com/1588744/127297324-99224807-c039-4a65-a2d7-84cd1b435672.png)

**Desktop (please complete the following information):**
 - OS: WSL / Windows + Ubuntu
 - Browser: NA
 - Using Anaconda

**Additional context**
This bug is resolved if the algorithm is specified but the question here is more about what is the strategy to update dependencies.

**Comment by BenjaminPelletier** [comment]
The reason we specify explicit version numbers for dependencies is to avoid breaking our system when a dependency makes a breaking change -- requirements.txt is essentially a contract that says the code in this folder should work if the Python environment is configured as specified in this file.  We don't make any guarantees about code working when that contract is not satisfied, and in many cases, doing that would be impossible because different versions of dependencies are not compatible with each other.

The version of a dependency can be updated in a PR, but that PR should ensure that all apps and tools in the repository previously relying on the old version of the dependency still work after the dependency version has been updated.  Examples of PRs like this include #486, #478, #474, #469 (though this one was not fully successful; see #477), #463, etc.
