### ISSUE TITLE
Problem with command ./build.sh

### ISSUE THREAD

**Issue by bohousboom** [interuss/dss#631]
Hi, I am doing on my university research. I try to get command ./build.sh and then I took back -> 
DOCKER_URL environment variable was not set; built images to interuss-local/dss and interuss-local/dummy-oauth

If I run cmd ./run_locally..sh then I took back errors connected with this: 

Starting dss_sandbox_local-dss-crdb_1 ... 
Starting dss_sandbox_local-dss-dummy-oauth_1 ... error

Starting dss_sandbox_local-dss-crdb_1        ... error
e99110a9895a24238a5821c79a3153f04ea561bb85d5e7c75cadffcd1e0f318 not found

ERROR: for dss_sandbox_local-dss-crdb_1  Cannot start service local-dss-crdb: network be99110a9895a24238a5821c79a3153f04ea561bb85d5e7c75cadffcd1e0f318 not found

ERROR: for local-dss-dummy-oauth  Cannot start service local-dss-dummy-oauth: network be99110a9895a24238a5821c79a3153f04ea561bb85d5e7c75cadffcd1e0f318 not found

ERROR: for local-dss-crdb  Cannot start service local-dss-crdb: network be99110a9895a24238a5821c79a3153f04ea561bb85d5e7c75cadffcd1e0f318 not found
ERROR: Encountered errors while bringing up the project.

Please could anyone knows how to fix this? 

Thanks a lot

**Comment by BenjaminPelletier** [comment]
What task are you trying to accomplish and which instructions are you following?  What do you expect to happen, and what happens instead?  Completing the [bug report template](https://github.com/interuss/dss/issues/new?assignees=&labels=&template=bug_report.md) should gather all the necessary information to start addressing a bug report.  For general questions, [Slack](https://github.com/interuss/tsc#slack) or [the mailing list](https://github.com/interuss/tsc#mailing-list) would be a more appropriate discussion forum.

Specific to the information here, `./build.sh` does not exist from the repo root (instead, it's `build/build.sh`), and `./run_locally.sh` does not exist from the repo root, nor from the `build` folder where `./build.sh` exists -- there are multiple `run_locally.sh` files in the repo, so we need to know what you're trying to do/which one you're trying to use.  If you're trying to bring up a local stand-alone instance for development, the instructions are [here](https://github.com/interuss/dss/blob/master/build/dev/standalone_instance.md) and do not include running `build/build.sh`.

**Comment by hrishiballal** [comment]
Apologies, I have been a bit caught up and could not follow up, Yes basically, for WSL, I do a `sed -i 's/\r$//' filename` ([source](https://stackoverflow.com/questions/11616835/r-command-not-found-bashrc-bash-profile)) for all the .sh files in the `/build/dev` and `/build/dev/startup` directories if there is a issue. I need to re-check it on my side. I will do it later today.

**Comment by hrishiballal** [comment]
OK I have now been able to run / bring up DSS via Windows 10 + WSL. 
1) My `docker version` and `docker compose version` is below: 
![image](https://user-images.githubusercontent.com/1588744/144594297-86a4c932-43b5-4c76-8ed2-6d38cc3d9384.png)
2) Instead of `./run_locally.sh` , I ran `docker compose -f docker-compose_dss.yaml up` 
![image](https://user-images.githubusercontent.com/1588744/144594342-bb104625-24fa-473e-adea-fca36a6a0d7f.png)
3) When you run it like this it seems to be working: 
![image](https://user-images.githubusercontent.com/1588744/144594415-dd946f6a-e1da-4d7e-8508-982331b86c69.png)
![image](https://user-images.githubusercontent.com/1588744/144594426-32e011a2-8120-4c95-8d88-6b2b7ba783b8.png)

I think this has to do with the way Windows treats the `docker-compose`, I am running it without the `-` , sharing my Docker for Windows Desktop settings:
![image](https://user-images.githubusercontent.com/1588744/144594778-3c455313-e7e3-4320-9efd-ffc7ba4ce1db.png)

**Comment by BenjaminPelletier** [comment]
Closed due to inactivity
