### ISSUE TITLE
Coalesce Subscriptions per callback URL

### ISSUE THREAD

**Issue by BenjaminPelletier** [interuss/dss#789]
Currently, we report a Subscriber for each Subscription.  Instead, we should coalesce per URL so that each unique URL only produces one SubscriberToNotify.
---
Is it correct to assume that there is always only one subscription ?

_Originally posted by @barroco in https://github.com/interuss/dss/pull/784#discussion_r890210741_

**Comment by BenjaminPelletier** [comment]
There may be many Subscriptions with the same callback URL, but that callback URL only needs to be invoked once.  [The SubscriberToNotify structure](https://github.com/astm-utm/Protocol/blob/cb7cf962d3a0c01b5ab12502f5f54789624977bf/utm.yaml#L382) contains a list of Subscriptions that are triggering this (one) notification.

**Comment by Shastick** [comment]
This issue seems to have been about both version of RID's ISA handlers. These are handled in:

- #1105 and
- #1106 

From what I can see, the OIR and CR handlers for SCD are already [properly grouping notifications by callback url](https://github.com/interuss/dss/blob/b6ad9f9cfad2f0a563a7239ba5df21146947fd6f/pkg/scd/server.go#L15) (the RID v1 and v2 equivalents being added are practically identical)

Instantiations of the scd, ridv1 and ridv2 variants of `SubscriberToNotify` are now all done in contexts where we properly group, and I have not found other places in the DSS codebase where we do something similar, so I feel once #1105 and #1106 are merged, this issue can be closed.

**Comment by Shastick** [comment]
Implemented by #1105 and #1106
