### ISSUE TITLE
Mapping of geographical coordinates to points over Unit Sphere

### ISSUE THREAD

**Issue by cenieto** [interuss/dss#951]
**Additional context**
I have just started digging a little inside the dss implementation and I have some doubts on the mapping from a geographical zone and a S2 CellId.

As it is stated [here](https://s2geometry.io/about/overview#:~:text=The%20answer%20is,geodetic%20coordinates%20exclusively.) S2 maps points over a unit sphere to cell identifications, so I assume that mapping of geographical coordinates to spherical coordinates must be done in the DSS, but i have not been able to get the location on the dss code where this is performed.

* Am I right?
* Am I missing something?

Thanks in advance!

**Comment by BenjaminPelletier** [comment]
A DSS needs to be able to identify things that are relevant to an area, so our implementation keeps an index of what entities ([ASTM F3411](https://www.astm.org/f3411-22a.html) Identification Service Areas + Subscriptions, [ASTM F3548](https://www.astm.org/f3548-21.html) Operational Intents + Subscriptions + Constraints) are relevant to what areas.  The technical approach to this is currently that the [level 13](https://github.com/interuss/dss/blob/8a1f48cae2569d754779b1cb39472b7b5e39e233/pkg/geo/s2.go#L18) S2 cells in which an entity exists (the [S2 covering](https://s2geometry.io/devguide/examples/coverings.html)) are stored so that entity can be discovered given a list of S2 cells of interest.  Apart from coverings like this, the DSS does not need to interact with or know about geographical coordinates.  More about S2 may be found [here](https://s2geometry.io/devguide/s2cell_hierarchy), but a user of the DSS should not need to know anything about S2 (or even that S2 is used).  Could you elaborate on your use case or the context behind the question?

**Comment by cenieto** [comment]
I will try to be more explicit.

As explained [here](https://s2geometry.io/devguide/s2cell_hierarchy.html#:~:text=The%20purpose%20of%20the%20nonlinear%20(face%2C%20s%2C%20t)%20%E2%86%92%20(face%2C%20u%2C%20v)%20transformation%20is%20to%20make%20the%20cells%20roughly%20the%20same%20size%20on%20the%20sphere.%20This%20can%20be%20visualized%20as%20follows%3A) any point over the surface of one sphere is mapped to a cube side and from it to a CellId.

My understanding is that this is performed taking the spherical coordinates (lat, lon) of a point and perform the S2 mapping to CellId.

The doubt is that WGS84 coordinates are not spherical, so (lat1 in following sketch) for WGS84 do not match with the spherical (lat2).
 
![Untitled Diagram drawio](https://github.com/interuss/dss/assets/78493198/55e21b61-110c-421d-926e-39183b0a551a)

Therefore if I PUT an ISA in the DSS and define the shape using WGS84 I will obtain a set of CellIds covering this geometry different that if I define the shape using spherical coordinates.

I hope this adds more clarity to my doubt.

**Comment by BenjaminPelletier** [comment]
I think much of my confusion stems from "I will obtain a set of CellIds".  DSS clients do not ever see S2 cells nor know of their existence -- could you describe a sequence of events that leads, or could lead, to the potential problem?

On your diagram, why does the lat1 line intercept the X axis at a location that isn't the center of the sphere nor the center of the WGS84 ellipsoid?

The highlighted sentence in the link is describing a stretching function so that features on the cube project to features that are roughly the same size on the sphere.

Is [this](https://www.youtube.com/watch?v=comMs1cxYT4) maybe a helpful description?  Shapes described with latitude and longitude points are mapped into S2 cells when creating an entity, and an area of interest described with latitude and longitude points is mapped into S2 cells when querying for entities.  Even if this mapping was "wrong" in some way, the same mapping process is used for both the entity and the query, so entities should be discoverable via their grid cell IDs regardless of the mapping function between geospatial shapes and grid cells.  An earlier version of what would become the DSS used [slippy tiles](https://wiki.openstreetmap.org/wiki/Slippy_map_tilenames) as a grid system instead of S2.  [MGRS](https://en.wikipedia.org/wiki/Military_Grid_Reference_System) or [H3](https://h3geo.org/) could hypothetically be used as well.  The DSS requirements should be met regardless of which grid cell system (S2, slippy, MGRS, H3, etc) is chosen for an implementation.  See, e.g., [ASTM F3411-22a](https://www.astm.org/f3411-22a.html) A2.5.4, 4.8.9, 4.8.10.2, A2.2.5.2, A2.2.5.4.

To be clear, no knowledge of S2 should be needed to use, as a USS, any DSS implementation (including this one) according to requirements in ASTM F3411 or ASTM F3548.  Knowledge of S2 is only required when developing changes to this implementation, or when designing another DSS implementation to be interoperable with this implementation.

**Comment by cenieto** [comment]
First of all, I think I was not precise enough when describing my doubt. When saying "I will obtain a set of CellIds" I do not mean the USSP obtain a set of CellIds, but the internal process of the DSS mapping any type of entity to a set of CellIds prior to storage in its internal database.

In my diagram the line defining lat1 do not intercept the X axis at the centre of the sphere or the WGS84 ellipsoid due to the way WGS84 coordinates are defined, using the Local Zenith (local normal to the ellipsoid surface). I think this [link](https://gssc.esa.int/navipedia/index.php/Ellipsoidal_and_Cartesian_Coordinates_Conversion) has a clearer sketch than mine. 

Nevertheless I think the key point for me is [your comment](https://github.com/interuss/dss/issues/951#:~:text=Even%20if%20this%20mapping%20was%20%22wrong%22%20in%20some%20way%2C%20the%20same%20mapping%20process%20is%20used%20for%20both%20the%20entity%20and%20the%20query%2C%20so%20entities%20should%20be%20discoverable%20via%20their%20grid%20cell). No matter if the mapping is not 100% mathematically and geographically correct, it provides a bijective relationship between geometry and CellId. Enough for our purposes.

Only nuance could be to obtain the cell size, in meters, to show any interested stakeholder the real granularity of de DAR in a specific region. Nevertheless this is another topic, not related with the functionality of the system.

Thanks a lot for your support!
